# Nightly keras2onnx unit tests

jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:

      ############ TF Keras Unit Tests ############
      Python36-tf1.15:
        python.version: '3.6'
        ONNX_PATH: onnx==1.10.1
        TENSORFLOW_PATH: tensorflow==1.15.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

      Python37-tf2.1:
        python.version: '3.7'
        ONNX_PATH: onnx==1.10.1
        TENSORFLOW_PATH: tensorflow-cpu==2.1.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

      Python38-tf2.2:
        python.version: '3.8'
        ONNX_PATH: onnx==1.10.1
        TENSORFLOW_PATH: tensorflow-cpu==2.2.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

      Python38-tf2.3:
        python.version: '3.8'
        ONNX_PATH: onnx==1.10.1
        TENSORFLOW_PATH: tensorflow-cpu==2.3.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

      Python38-tf2.5:
        python.version: '3.8'
        ONNX_PATH: onnx==1.10.1
        TENSORFLOW_PATH: tensorflow-cpu==2.5.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

      ############ Pure Keras Unit Tests ############
      Keras-Py36-tf1.15.0:
        python.version: '3.6'
        ONNX_PATH: onnx==1.10.1
        KERAS: keras==2.2.5
        TENSORFLOW_PATH: tensorflow==1.15.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

      Keras-Py37-tf1.15.0:
        python.version: '3.7'
        ONNX_PATH: onnx==1.10.1
        KERAS: keras==2.4.3
        TENSORFLOW_PATH: tensorflow==1.15.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

      # UT for keras 2.3 need tensorflow <= 2.0.0
      Keras-Py37-tf2.0.0:
        python.version: '3.7'
        ONNX_PATH: onnx==1.10.1
        KERAS: keras==2.3.1
        TENSORFLOW_PATH: tensorflow==2.0.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

      Keras-Py38-tf2.2.0:
        python.version: '3.8'
        ONNX_PATH: onnx==1.10.1
        KERAS: keras==2.4.3
        TENSORFLOW_PATH: tensorflow==2.2.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

  steps:
  - template: 'templates/keras2onnx_unit_test.yml'
    parameters:
      platform: 'linux'

- job: 'Win'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      ############ TF Keras Unit Tests ############
      Python36-tf-1.15:
        python.version: '3.6'
        ONNX_PATH: onnx==1.10.1
        TENSORFLOW_PATH: tensorflow==1.15.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

      Python37-tf2.1:
        python.version: '3.7'
        ONNX_PATH: onnx==1.10.1
        TENSORFLOW_PATH: tensorflow-cpu==2.1.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

      Python37-tf2.2:
        python.version: '3.7'
        ONNX_PATH: onnx==1.10.1
        TENSORFLOW_PATH: tensorflow-cpu==2.2.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

      Python37-tf2.3:
        python.version: '3.7'
        ONNX_PATH: onnx==1.10.1
        TENSORFLOW_PATH: tensorflow-cpu==2.3.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

      Python37-tf2.5:
        python.version: '3.7'
        ONNX_PATH: onnx==1.10.1
        TENSORFLOW_PATH: tensorflow-cpu==2.5.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

      ############ Pure Keras Unit Tests ############
      Keras-Py36-tf1.15.0:
        python.version: '3.6'
        ONNX_PATH: onnx==1.10.1
        KERAS: keras==2.2.5
        TENSORFLOW_PATH: tensorflow==1.15.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

      Keras-Py37-tf2.0.0:
        python.version: '3.7'
        ONNX_PATH: onnx==1.10.1
        KERAS: keras==2.3.1
        TENSORFLOW_PATH: tensorflow==2.0.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

      Keras-Py37-tf2.2.0:
        python.version: '3.7'
        ONNX_PATH: onnx==1.10.1
        KERAS: keras==2.4.3
        TENSORFLOW_PATH: tensorflow==2.2.0
        INSTALL_ORT: pip install onnxruntime==1.9.0

  steps:
  - template: 'templates/keras2onnx_unit_test.yml'
    parameters:
      platform: 'windows'
