# Test against latest onnxruntime nightly package

# TODO: change package name when nightly build is ready

# Unit test
jobs:
- template: 'templates/job_generator.yml'
  parameters:
    tf_versions: ['1.12']
    onnx_opsets: ['9', '8', '7']
    onnx_backends:
      onnxruntime: []
    job:
      steps:
      - template: 'unit_test.yml'

# Pre-trained model test
jobs:
- template: 'templates/job_generator.yml'
  parameters:
    tf_versions: ['1.12']
    onnx_opsets: ['9', '8', '7']
    onnx_backends:
      onnxruntime: []
    job:
      steps:
      - template: 'pretrained_model_test.yml'
