# Test against latest onnxruntime nightly package

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    tf_versions: ['1.13.1']
    onnx_opsets: ['']
    onnx_backends:
      onnxruntime: ['']
    job:
      steps:
      - template: 'unit_test.yml'
        parameters:
            onnx_opsets: ['10', '9', '8', '7']
    report_coverage: 'True'

- template: 'templates/combine_test_coverage.yml'
