# Test against latest onnxruntime nightly package

stages:
  - stage:
    jobs:
    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: [3.7']
        tf_versions: ['1.15.5']
        onnx_backends: {onnxruntime: ['nightly']}
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: ['3.8']
        tf_versions: ['2.8.0', '2.9.0', '2.13.0']
        onnx_backends: {onnxruntime: ['nightly']}
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: ['3.9']
        tf_versions: ['2.10.0', '2.12.0']
        onnx_backends: {onnxruntime: ['nightly']}
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: ['3.10']
        tf_versions: ['2.8.0', '2.13.0']
        onnx_backends: {onnxruntime: ['nightly']}
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

  - template: 'templates/combine_test_coverage.yml'

schedules:
- cron: "0 10 * * *"
  displayName: Daily onnxruntime nightly unittest
  branches:
    include:
    - main
  always: true
