# Test against latest onnxruntime nightly package

stages:
  - stage:
    jobs:
    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: ['3.7', '3.6']
        tf_versions: ['1.13.1']
        onnx_opsets: ['']
        onnx_backends: {onnxruntime: ['nightly']}
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: [3.7', '3.6']
        tf_versions: ['1.14.0']
        onnx_opsets: ['']
        onnx_backends: {onnxruntime: ['nightly']}
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: [3.7']
        tf_versions: ['1.15.2','2.1.0']
        onnx_opsets: ['']
        onnx_backends: {onnxruntime: ['nightly']}
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'
  
    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: [3.8']
        tf_versions: ['2.5.0rc1']
        onnx_opsets: ['']
        onnx_backends: {onnxruntime: ['nightly']}
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'
  
  - template: 'templates/combine_test_coverage.yml'

schedules:
- cron: "0 10 * * *"
  displayName: Daily onnxruntime nightly unittest
  branches:
    include:
    - master
  always: true
