# Test against latest onnxruntime nightly package

stages:
  - stage:
    jobs:
    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: [3.7']
        tf_versions: ['1.15.5']
        onnx_versions: ['1.14.1'] # Max version that supports python 3.7
        onnx_backends: {onnxruntime: ['nightly']}
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: ['3.8']
        tf_versions: ['2.9.0', '2.10.0']
        onnx_backends: {onnxruntime: ['nightly']}
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: ['3.9']
        tf_versions: ['2.11.0', '2.12.0']
        onnx_backends: {onnxruntime: ['nightly']}
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: ['3.10']
        tf_versions: ['2.13.0', '2.15.0']
        onnx_backends: {onnxruntime: ['nightly']}
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

  - template: 'templates/combine_test_coverage.yml'

schedules:
- cron: "0 12 */3 * *"
  displayName: Every 3 days onnxruntime nightly unittest
  branches:
    include:
    - main
  always: true
