# Pre-trained model test

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    python_versions: ['3.7']
    tf_versions: ['1.15.2','2.1.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    python_versions: [3.6']
    tf_versions: ['1.14.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['windows']
    tf_versions: ['1.14.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'
