# Pre-trained model test

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    # 2.6, tflite/tfjs
    python_versions: ['3.8']
    tf_versions: ['2.6.2']
    skip_tflite_tests: 'False'
    skip_tfjs_tests: 'False'
    skip_tf_tests: 'True'
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    # 2.8, tf
    python_versions: ['3.7']
    tf_versions: ['1.15.5','2.8.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    # 2.10, tf
    python_versions: ['3.10']
    tf_versions: ['2.9.1']
    job:
      steps:
      - template: 'pretrained_model_test.yml'
