# Pre-trained model test, full matrix

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows', 'mac']
    python_versions: ['3.6', '3.5']
    tf_versions: ['1.13.1', '1.12', '1.11', '1.10', '1.9', '1.8', '1.7', '1.6', '1.5']
    onnx_opsets: ['9', '8', '7']
    job:
      steps:
      - template: 'pretrained_model_test.yml'
