# Pre-trained model test, full matrix

jobs:

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['windows']
    python_versions: ['3.7'] # Max version that supports tf 1.15
    tf_versions: ['1.15.5']
    onnx_versions: ['1.14.1'] # Max version that supports python 3.7
    onnx_opsets: ['18', '17', '16', '15', '14']
    onnx_backends: {onnxruntime: ['1.14.1']} # Max version that supports python 3.7
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux']
    python_versions: ['3.7'] # Max version that supports tf 1.15
    tf_versions: ['1.15.5']
    onnx_versions: ['1.14.1'] # Max version that supports python 3.7
    onnx_opsets: ['18', '17', '16', '14']
    onnx_backends: {onnxruntime: ['1.14.1']} # Max version that supports python 3.7
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['windows']
    python_versions: ['3.9']
    tf_versions: ['2.9.0', '2.15.0']
    onnx_opsets: ['18', '17', '16', '15']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux']
    python_versions: ['3.8']
    tf_versions: ['2.9.0']
    onnx_opsets: ['17', '16', '14']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux']
    python_versions: ['3.10']
    tf_versions: ['2.15.0']
    onnx_opsets: ['17', '16', '14']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.8']
    tf_versions: ['2.10.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.9']
    tf_versions: ['2.11.0', '2.12.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.10']
    tf_versions: ['2.14.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

schedules:
- cron: "0 11 */3 * *"
  displayName: pre-trained model test, full matrix, run every 3 days
  branches:
    include:
    - main
  always: true
