# Pre-trained model test, full matrix

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.7']
    tf_versions: ['1.14.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.7']
    tf_versions: ['1.15.2','2.1.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.8']
    tf_versions: ['2.7.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.8']
    tf_versions: ['2.8.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.9']
    tf_versions: ['2.9.1']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.10']
    tf_versions: ['2.9.1']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

schedules:
- cron: "0 10 * * *"
  displayName: pre-trained model test, full matrix
  branches:
    include:
    - main
  always: true
