# Pre-trained model test, full matrix

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.6']
    tf_versions: ['1.13.1', '1.12.3']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.7', '3.6']
    tf_versions: ['1.14.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.7']
    tf_versions: ['1.15.2','2.1.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.8']
    tf_versions: ['2.5.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.9']
    tf_versions: ['2.6.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

schedules:
- cron: "0 10 * * *"
  displayName: pre-trained model test, full matrix
  branches:
    include:
    - master
  always: true
