# Pre-trained model test

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    python_versions: ['3.7'] # Max version that supports tf 1.15
    tf_versions: ['1.15.5']
    onnx_opsets: ['18', '17', '16', '15', '14']
    onnx_backends: {onnxruntime: ['1.14.1']} # Max version that supports python 3.7
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    python_versions: ['3.8']
    tf_versions: ['2.8.0', '2.13.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    python_versions: ['3.10']
    tf_versions: ['2.8.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'
