# Pre-trained model test

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    # 2.7, tf
    python_versions: ['3.7']
    tf_versions: ['2.7.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    # 2.8, tf
    python_versions: ['3.9']
    tf_versions: ['2.8.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.8']
    tf_versions: ['2.7.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows']
    python_versions: ['3.8']
    tf_versions: ['2.8.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'