# Pre-trained model test

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    python_versions: ['3.8']
    tf_versions: ['1.15.2','2.4.0']
    job:
      steps:
      - template: 'pretrained_model_test.yml'
