# Pre-trained model test

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    python_versions: ['3.7']
    tf_versions: ['2.4.1']
    skip_tflite_tests: 'False'
    skip_tf_tests: 'True'
    job:
      steps:
      - template: 'pretrained_model_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    python_versions: ['3.7']
    tf_versions: ['1.15.5','2.4.1']
    job:
      steps:
      - template: 'pretrained_model_test.yml'
