# Tests copied from keras2onnx

jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:

      ############ TF Keras Unit Tests ############
      02-Python38-tf2.9:
        python.version: '3.8'
        ONNX_PATH: onnx==1.11.0
        TENSORFLOW_PATH: tensorflow-cpu==2.9.0
        INSTALL_ORT: pip install -i https://test.pypi.org/simple/ ort-nightly==1.12.0.dev20220707003
        INSTALL_NUMPY:

      06-Python38-tf2.8:
        python.version: '3.8'
        ONNX_PATH: onnx==1.11.0
        TENSORFLOW_PATH: tensorflow-cpu==2.8.0
        INSTALL_ORT: pip install -i https://test.pypi.org/simple/ ort-nightly==1.12.0.dev20220707003
        INSTALL_NUMPY:

  steps:
  - template: 'templates/keras2onnx_unit_test.yml'
    parameters:
      platform: 'linux'

- job: 'Win'
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      ############ TF Keras Unit Tests ############
      Python37-tf2.8:
        python.version: '3.8'
        ONNX_PATH: onnx==1.11.0
        TENSORFLOW_PATH: tensorflow-cpu==2.8.0
        INSTALL_ORT: pip install -i https://test.pypi.org/simple/ ort-nightly==1.12.0.dev20220707003
        INSTALL_NUMPY:

      Python38-tf2.9:
        python.version: '3.8'
        ONNX_PATH: onnx==1.11.0
        TENSORFLOW_PATH: tensorflow-cpu==2.9.0
        INSTALL_ORT: pip install onnxruntime==1.11.0
        INSTALL_NUMPY:

  steps:
  - template: 'templates/keras2onnx_unit_test.yml'
    parameters:
      platform: 'windows'
