# Tests copied from keras2onnx

jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:

      ############ TF Keras Unit Tests ############
      Python37-tf1.15:
        python.version: '3.7'
        ONNX_PATH: onnx==1.11.0
        TENSORFLOW_PATH: tensorflow==1.15.0
        INSTALL_ORT: pip install onnxruntime==1.11.0
        INSTALL_NUMPY: pip install numpy==1.19.0

      Python38-tf2.9:
        python.version: '3.8'
        ONNX_PATH: onnx==1.11.0
        TENSORFLOW_PATH: tensorflow-cpu==2.9.0
        INSTALL_ORT: pip install onnxruntime==1.11.0
        INSTALL_NUMPY:

      ############ Pure Keras Unit Tests ############
      Keras-Py37-tf1.15.0:
        python.version: '3.7'
        ONNX_PATH: onnx==1.11.0
        KERAS: keras==2.4.3
        TENSORFLOW_PATH: tensorflow==1.15.0
        INSTALL_ORT: pip install onnxruntime==1.11.0
        INSTALL_NUMPY: pip install numpy==1.19.0

      # UT for keras 2.3 need tensorflow <= 2.0.0
      Keras-Py37-tf2.0.0:
        python.version: '3.7'
        ONNX_PATH: onnx==1.11.0
        KERAS: keras==2.3.1
        TENSORFLOW_PATH: tensorflow==2.0.0
        INSTALL_ORT: pip install onnxruntime==1.11.0
        INSTALL_NUMPY: pip install numpy==1.19.0

      Keras-Py310-tf2.9.0:
        python.version: '3.10'
        ONNX_PATH: -i onnx==1.12.0
        TENSORFLOW_PATH: tensorflow==2.9.0
        INSTALL_ORT: pip install onnxruntime==1.12.0
        INSTALL_NUMPY:

  steps:
  - template: 'templates/keras2onnx_unit_test.yml'
    parameters:
      platform: 'linux'

- job: 'Win'
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      ############ TF Keras Unit Tests ############
      Python37-tf-1.15:
        python.version: '3.7'
        ONNX_PATH: onnx==1.11.0
        TENSORFLOW_PATH: tensorflow==1.15.0
        INSTALL_ORT: pip install onnxruntime==1.11.0
        INSTALL_NUMPY: pip install numpy==1.19.0

      Python38-tf2.9:
        python.version: '3.8'
        ONNX_PATH: onnx==1.11.0
        TENSORFLOW_PATH: tensorflow-cpu==2.9.0
        INSTALL_ORT: pip install onnxruntime==1.11.0
        INSTALL_NUMPY:

      Python310-tf2.9:
        python.version: '3.10'
        ONNX_PATH: onnx==1.12.0
        TENSORFLOW_PATH: tensorflow-cpu==2.9.0
        INSTALL_ORT: pip install onnxruntime==1.12.0
        INSTALL_NUMPY:

      ############ Pure Keras Unit Tests ############
      Keras-Py37-tf2.2.0:
        python.version: '3.7'
        ONNX_PATH: onnx==1.11.0
        KERAS: keras==2.4.3
        TENSORFLOW_PATH: tensorflow==2.2.0
        INSTALL_ORT: pip install onnxruntime==1.11.0
        INSTALL_NUMPY: pip install numpy==1.19.0

  steps:
  - template: 'templates/keras2onnx_unit_test.yml'
    parameters:
      platform: 'windows'
