# Tests copied from keras2onnx

jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:

  steps:
  - template: 'templates/keras2onnx_unit_test.yml'
    parameters:
      platform: 'linux'