# Unit test

stages:
  - stage:
    jobs:
    - template: 'templates/job_generator.yml'
      parameters:
        python_versions: ['3.7', '3.6']
        tf_versions: ['1.14', '1.15']
        platforms: ['linux']
        onnx_opsets: ['11', '10', '9', '8', '7']
        onnx_backends: {onnxruntime: ['nightly']}
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'
    
  - template: 'templates/combine_test_coverage.yml'
