# Unit test, full matrix

stages:
  - stage:
    jobs:
    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: ['3.7', '3.6']
        tf_versions: ['1.13.1', '1.12']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'
    
    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: ['3.8', '3.7', '3.6']
        tf_versions: ['1.14']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

  - template: 'templates/combine_test_coverage.yml'
