# Unit test

stages:
  - stage:
    jobs:
    - template: 'templates/job_generator.yml'
      parameters:
        python_versions: ['3.8']
        tf_versions: ['2.5.0']
        onnx_opsets: ['']
        skip_tflite_tests: 'False'
        skip_tf_tests: 'True'
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        python_versions: ['3.7']
        tf_versions: ['2.3.0']
        onnx_opsets: ['']
        skip_tflite_tests: 'False'
        skip_tf_tests: 'True'
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        python_versions: ['3.8']
        tf_versions: ['2.5.0']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        python_versions: ['3.7']
        tf_versions: ['1.14.0','1.15.2','2.3.0','2.4.1']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        python_versions: [3.6']
        tf_versions: ['1.12.3']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['windows']
        tf_versions: ['1.14.0']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        python_versions: ['3.7']
        platforms: ['windows']
        tf_versions: ['2.4.1']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

  - template: 'templates/combine_test_coverage.yml'

