# Unit test

stages:
  - stage:
    jobs:
    - template: 'templates/job_generator.yml'
      parameters:
        python_versions: ['3.7']
        tf_versions: ['1.14.0','1.15.2','2.1.0']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'
    
    - template: 'templates/job_generator.yml'
      parameters:
        python_versions: [3.6']
        tf_versions: ['1.12.3']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'
    
    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['windows']
        tf_versions: ['1.14.0']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

  - template: 'templates/combine_test_coverage.yml'
