# Unit test, full matrix

stages:
  - stage:
    jobs:
    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: ['3.7']
        tf_versions: ['1.14.0', '1.15.2']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: ['3.8']
        tf_versions: ['2.5.0']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'
  
    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: ['3.8']
        tf_versions: ['2.6.2']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: ['3.9', '3.10']
        tf_versions: ['2.8.0']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['linux', 'windows']
        python_versions: ['3.9']
        tf_versions: ['2.9.0']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

  - template: 'templates/combine_test_coverage.yml'
