# Unit test

stages:
  - stage:
    jobs:
    - template: 'templates/job_generator.yml'
      parameters:
        # TFJS tf 2.8
        python_versions: ['3.9']
        tf_versions: ['2.8.0']
        onnx_opsets: ['']
        skip_tfjs_tests: 'False'
        skip_tf_tests: 'True'
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        # TFLite tf 2.8
        python_versions: ['3.8']
        tf_versions: ['2.8.0']
        onnx_opsets: ['']
        skip_tflite_tests: 'False'
        skip_tf_tests: 'True'
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        # tf 2.8
        python_versions: ['3.8']
        tf_versions: ['2.8.0']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        # TFJS tf 2.7
        python_versions: ['3.9']
        tf_versions: ['2.7.0']
        onnx_opsets: ['']
        skip_tfjs_tests: 'False'
        skip_tf_tests: 'True'
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        # TFLite tf 2.7
        python_versions: ['3.8']
        tf_versions: ['2.7.0']
        onnx_opsets: ['']
        skip_tflite_tests: 'False'
        skip_tf_tests: 'True'
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        # tf 2.7
        python_versions: ['3.8']
        tf_versions: ['2.7.0']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        # TFJS tf 2.9
        python_versions: ['3.10']
        tf_versions: ['2.9.1']
        onnx_opsets: ['']
        skip_tfjs_tests: 'False'
        skip_tf_tests: 'True'
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        # TFLite tf 2.9
        python_versions: ['3.10']
        tf_versions: ['2.9.1']
        onnx_opsets: ['']
        skip_tflite_tests: 'False'
        skip_tf_tests: 'True'
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        # tf 2.9
        python_versions: ['3.10']
        tf_versions: ['2.9.1']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      # tf 2.5, tf 1.15
      parameters:
        python_versions: ['3.7']
        tf_versions: ['1.15.2','2.5.0']
        onnx_opsets: ['']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        platforms: ['windows']
        tf_versions: ['1.14.0']
        onnx_opsets: ['14']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        python_versions: ['3.7']
        platforms: ['windows']
        tf_versions: ['2.4.1']
        onnx_opsets: ['13']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        python_versions: ['3.8']
        platforms: ['windows']
        tf_versions: ['2.8.1']
        onnx_opsets: ['15']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        python_versions: ['3.9']
        platforms: ['windows']
        tf_versions: ['2.9.1']
        onnx_opsets: ['16']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        python_versions: ['3.10']
        platforms: ['windows']
        tf_versions: ['2.9.1']
        onnx_opsets: ['17']
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

  - template: 'templates/combine_test_coverage.yml'

