# Unit test

stages:
  - stage:
    jobs:
    - template: 'templates/job_generator.yml'
      parameters:
        python_versions: ['3.8']
        platforms: ['linux', 'windows']
        tf_versions: ['2.8.0', '2.13.0']
        onnx_opsets: ['18', '17', '16', '15']
        skip_tflite_tests: 'False'
        skip_tf_tests: 'False'
        skip_tfjs_tests: 'True'
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    - template: 'templates/job_generator.yml'
      parameters:
        python_versions: ['3.7'] # Max version that supports tf 1.15
        platforms: ['linux']
        tf_versions: ['1.15.5']
        onnx_opsets: ['18', '17', '16', '15']
        onnx_backends: {onnxruntime: ['1.14.1']} # Max version that supports python 3.7
        job:
          steps:
          - template: 'unit_test.yml'
        report_coverage: 'True'

    # TODO: Enable these tests once https://github.com/onnx/tensorflow-onnx/issues/2118 is fixed.
    # - template: 'templates/job_generator.yml'
    #   parameters:
    #     python_versions: ['3.9']
    #     tf_versions: ['2.8.0']
    #     onnx_opsets: ['']
    #     skip_tfjs_tests: 'False'
    #     skip_tf_tests: 'True'
    #     job:
    #       steps:
    #       - template: 'unit_test.yml'
    #     report_coverage: 'True'

    # TODO: Enable these tests once https://github.com/onnx/tensorflow-onnx/issues/2118 is fixed.
    # - template: 'templates/job_generator.yml'
    #   parameters:
    #     python_versions: ['3.9']
    #     tf_versions: ['2.7.4']
    #     onnx_opsets: ['']
    #     skip_tfjs_tests: 'False'
    #     skip_tf_tests: 'True'
    #     job:
    #       steps:
    #       - template: 'unit_test.yml'
    #     report_coverage: 'True'

    # TODO: Enable these tests once https://github.com/onnx/tensorflow-onnx/issues/2118 is fixed.
    # - template: 'templates/job_generator.yml'
    #   parameters:
    #     python_versions: ['3.10']
    #     tf_versions: ['2.9.1']
    #     onnx_opsets: ['']
    #     skip_tfjs_tests: 'False'
    #     skip_tf_tests: 'True'
    #     job:
    #       steps:
    #       - template: 'unit_test.yml'
    #     report_coverage: 'True'

  - template: 'templates/combine_test_coverage.yml'
