name: Keras2onnx Application Test Run

inputs:
  tf_version:
    description: 'TensorFlow version'
  python_version:
    description: 'Python version'
  ort_version:
    description: 'ONNXRuntime version'
  onnx_version:
    description: 'ONNX version'

runs:
  using: "composite"
  steps:
    - name: Set up Python (${{ inputs.python_version }})
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install dependencies (TF-v${{ inputs.tf_version }})
      shell: bash
      run: |
          python -m pip install --upgrade pip
          pip install onnxconverter-common
          pip install onnx==${{ inputs.onnx_version }}
          pip install h5py
          pip install parameterized
          pip install timeout-decorator
          pip install coloredlogs flatbuffers
          pip install onnxruntime==${{ inputs.ort_version }}
          pip install pillow
          pip install opencv-python
          pip install tqdm
          pip install keras-segmentation==0.2.0
          git clone https://github.com/matterport/Mask_RCNN
          cd Mask_RCNN
          pip install -r requirements.txt
          python setup.py install
          cd ..
          pip install matplotlib
          git clone https://github.com/qqwweee/keras-yolo3
          pip install keras-resnet
          pip install git+https://www.github.com/keras-team/keras-contrib.git
          pip install keras-tcn==2.8.3
          pip install git+https://github.com/qubvel/efficientnet
          pip install keras-self-attention
          pip install pytest pytest-cov pytest-runner
          pip uninstall -y protobuf h5py

          if [[ ${{ inputs.tf_version }} == 1.* ]]; then 
              echo "-- install-1 TF1-KERAS ${{ inputs.tf_version }}"
              pip install numpy==1.19.0 tensorflow==${{ inputs.tf_version }} protobuf h5py==2.9.0 transformers==4.2.0 keras h5py
          else 
              pip install transformers
              if [[ "${{ inputs.tf_version }}" != "2.13.0" && "${{ inputs.tf_version }}" != "2.9.0" ]]; then
                echo "-- install-1 TF-KERAS ${{ inputs.tf_version }}"
                pip install tf_keras==${{ inputs.tf_version }} tensorflow==${{ inputs.tf_version }} protobuf
              else
                echo "-- install-1 TF ${{ inputs.tf_version }}"
                pip install protobuf tensorflow==${{ inputs.tf_version }}
              fi
          fi

          pip install -e .

          echo "----- List all of depdencies:"
          pip freeze --all

    - name: Run keras_application_test (${{ runner.os }})
      shell: bash
      run: |
          python -c "import onnxruntime"
          pytest tests/keras2onnx_unit_tests --doctest-modules --junitxml=junit/test-results.xml

          export TF_USE_LEGACY_KERAS=True
          cd tests/keras2onnx_applications/nightly_build
          python run_all_v2.py
