name: Keras Unit Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:

  test:
    timeout-minutes: 60
    permissions:
      actions: write
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-2022']
        tf_version: ['2.13.0', '2.15.0']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/keras_unit_test
        with:
          tf_version: ${{ matrix.tf_version }}
          python_version: '3.10'
          ort_version: '1.16.3'
          onnx_version: '1.16.1'
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: Test Results (${{ matrix.os }}-tf${{ matrix.tf_version }})
          path: junit/test-results.xml

  publish-test-results:
    name: "Publish Tests Results to Github"
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          path: artifacts
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        with:
          files: "artifacts/**/*.xml"
