# Copyright (c) ONNX Project Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: Keras Application Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:

  test:
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-2022']
        tf_version: ['2.13.0', '2.15.0']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/keras_application_test
        with:
          tf_version: ${{ matrix.tf_version }}
          python_version: '3.10'
          ort_version: '1.16.3'
          onnx_version: '1.16.1'
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: Test Results (${{ matrix.os }}-tf${{ matrix.tf_version }})
          path: junit/test-results.xml

  publish-test-results:
    name: "Publish Tests Results to Github"
    needs: [test]
    if: always()
    permissions:
      checks: write
      pull-requests: write
    uses: ./.github/workflows/publish-test-results.yml
